/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControllerPlaylist;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import model.Musica;

/**
 *
 * @author Mixzq
 */
public class ExcluirMusicaFrame extends javax.swing.JFrame {

    /**
     * Creates new form ExcluirMusicaFrame
     */
private String usuario;
    private int idUsuario;
    private int idPlaylist;
    private String nomePlaylist;
    private ControllerPlaylist c;
    ArrayList <Musica> musicas;
    public ExcluirMusicaFrame(String username, int id, int idPlaylist, 
                                 String nomePlaylist) {
        initComponents();
        this.usuario = username;
        this.idUsuario = id; 
        this.idPlaylist = idPlaylist;
        this.nomePlaylist = nomePlaylist;
        this.c = new ControllerPlaylist(this.usuario, this.idUsuario,this,
                this.idPlaylist);
        titulo11.setText(nomePlaylist);

        musicas = c.retornarMusicasDaPlaylistCompleto();
        for(Musica m : musicas){
            System.out.println(m.getNome());
        }
        mostrarMusicas(musicas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        titulo9 = new javax.swing.JLabel();
        telaMostrar = new javax.swing.JPanel();
        telaMostrar2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        titulo10 = new javax.swing.JLabel();
        titulo11 = new javax.swing.JLabel();
        telaMostrar3 = new javax.swing.JPanel();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Excluir músicas");

        jPanel17.setBackground(new java.awt.Color(144, 238, 144));
        jPanel17.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel18.setBackground(new java.awt.Color(51, 51, 51));
        jPanel18.setForeground(new java.awt.Color(102, 102, 102));

        titulo9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titulo9.setForeground(new java.awt.Color(73, 151, 51));
        titulo9.setText("Spotifei");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulo9)
                .addGap(571, 571, 571))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(titulo9)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        telaMostrar.setBackground(new java.awt.Color(144, 238, 144));

        javax.swing.GroupLayout telaMostrarLayout = new javax.swing.GroupLayout(telaMostrar);
        telaMostrar.setLayout(telaMostrarLayout);
        telaMostrarLayout.setHorizontalGroup(
            telaMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );
        telaMostrarLayout.setVerticalGroup(
            telaMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        telaMostrar2.setBackground(new java.awt.Color(144, 238, 144));

        javax.swing.GroupLayout telaMostrar2Layout = new javax.swing.GroupLayout(telaMostrar2);
        telaMostrar2.setLayout(telaMostrar2Layout);
        telaMostrar2Layout.setHorizontalGroup(
            telaMostrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );
        telaMostrar2Layout.setVerticalGroup(
            telaMostrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 733, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        titulo10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titulo10.setForeground(new java.awt.Color(144, 238, 144));
        titulo10.setText("Playlist");

        titulo11.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titulo11.setForeground(new java.awt.Color(144, 238, 144));
        titulo11.setText("NOME");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(516, 516, 516)
                .addComponent(titulo10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titulo11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo10)
                    .addComponent(titulo11))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        telaMostrar3.setBackground(new java.awt.Color(144, 238, 144));

        javax.swing.GroupLayout telaMostrar3Layout = new javax.swing.GroupLayout(telaMostrar3);
        telaMostrar3.setLayout(telaMostrar3Layout);
        telaMostrar3Layout.setHorizontalGroup(
            telaMostrar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        telaMostrar3Layout.setVerticalGroup(
            telaMostrar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnVoltar.setBackground(new java.awt.Color(204, 204, 204));
        btnVoltar.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addComponent(telaMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telaMostrar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telaMostrar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(telaMostrar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(telaMostrar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(telaMostrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVoltar)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1214, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 906, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.setVisible(false);
        EditarPlaylistFrame hm = new EditarPlaylistFrame(usuario,idUsuario);
        hm.setLocationRelativeTo(null);
        hm.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    public void mostrarMusicas(ArrayList <Musica> musicas) {
        telaMostrar.removeAll();
        telaMostrar2.removeAll();
        telaMostrar3.removeAll();

        telaMostrar.setLayout(new BoxLayout(telaMostrar, BoxLayout.Y_AXIS));
        telaMostrar2.setLayout(new BoxLayout(telaMostrar2, BoxLayout.Y_AXIS));
        telaMostrar3.setLayout(new BoxLayout(telaMostrar3, BoxLayout.Y_AXIS));

        if (musicas.isEmpty()) {
            JLabel lblNaoEncontrado = new JLabel("Ops! Nenhuma música encontrada!");
            JLabel lblNaoEncontrado2 = new JLabel(":C");
            lblNaoEncontrado.setFont(new Font("Segoe UI", Font.BOLD, 25));
            lblNaoEncontrado.setAlignmentX(Component.CENTER_ALIGNMENT);
            lblNaoEncontrado2.setFont(new Font("Segoe UI", Font.BOLD, 25));
            lblNaoEncontrado2.setAlignmentX(Component.CENTER_ALIGNMENT);
            telaMostrar.add(lblNaoEncontrado);
            telaMostrar.add(lblNaoEncontrado2);

            telaMostrar.revalidate();
            telaMostrar.repaint();
            return;
        }

        int limite = Math.min(musicas.size(), 15); // Até 15 músicas (5 por coluna)

        for (int i = 0; i < limite; i++) {
            Musica m = musicas.get(i);

            JPanel musicaPanel = new JPanel();
            musicaPanel.setLayout(new BoxLayout(musicaPanel, BoxLayout.X_AXIS));
            musicaPanel.setBackground(new java.awt.Color(144, 238, 144));
            musicaPanel.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(new java.awt.Color(60, 179, 113), 1),
                BorderFactory.createEmptyBorder(3, 15, 10, 15)
            ));

            JPanel painelEsquerdo = new JPanel();
            painelEsquerdo.setLayout(new BoxLayout(painelEsquerdo, BoxLayout.Y_AXIS));
            painelEsquerdo.setBackground(new java.awt.Color(144, 238, 144));

            JLabel lblNome = new JLabel(m.getNome());
            lblNome.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 20));
            lblNome.setAlignmentX(Component.LEFT_ALIGNMENT);
            painelEsquerdo.add(lblNome);

            JLabel lblArtista = new JLabel("<html><b>Artista:</b> " 
                    + m.getArtista().getNomeArtistico() + "</html>");
            JLabel lblGenero = new JLabel("<html><b>Gênero:</b> " 
                    + m.getGenero() + "</html>");
            JLabel lblAno = new JLabel("<html><b>Ano:</b> " 
                    + m.getAnoLancamento() + "</html>");
            JLabel lblAlbum = new JLabel("<html><b>Álbum:</b> " 
                    + m.getAlbum() + "</html>");

            Font fonte = new Font("Segoe UI Semibold", Font.PLAIN, 15);
            for (JLabel lbl : new JLabel[]{lblArtista, lblGenero, lblAno, lblAlbum}) {
                lbl.setFont(fonte);
                lbl.setAlignmentX(Component.LEFT_ALIGNMENT);
                painelEsquerdo.add(lbl);
            }

            // BTN REMOVER DIREITA
            JPanel painelDireito = new JPanel();
            painelDireito.setLayout(new BoxLayout(painelDireito, BoxLayout.Y_AXIS));
            painelDireito.setBackground(new java.awt.Color(144, 238, 144));

            // BTN REMOVER
            JButton btnRemover = new JButton("X");
            btnRemover.setBackground(new java.awt.Color(204,0,51)); 
            btnRemover.setForeground(new java.awt.Color(255, 255, 255)); 
            btnRemover.setPreferredSize(new java.awt.Dimension(50, 50)); 
            btnRemover.setMaximumSize(new java.awt.Dimension(42, 42)); 
            btnRemover.addActionListener(e -> {
                int idMusica = m.getId();

                c.removerMusicaNaPlaylist(idPlaylist, idMusica);
            });
            painelDireito.add(btnRemover);  

            musicaPanel.add(painelEsquerdo);
            musicaPanel.add(painelDireito);

            musicaPanel.setPreferredSize(new java.awt.Dimension(400, 130));
            musicaPanel.setMaximumSize(new java.awt.Dimension(400, 130));

            if (i < 5) {
                telaMostrar.add(musicaPanel);
                telaMostrar.add(Box.createVerticalStrut(8));
            } else if (i < 10) {
                musicaPanel.setPreferredSize(new java.awt.Dimension(400, 129));
                musicaPanel.setMaximumSize(new java.awt.Dimension(400, 129));
                telaMostrar2.add(musicaPanel);
                telaMostrar2.add(Box.createVerticalStrut(8));
            } else {
                musicaPanel.setPreferredSize(new java.awt.Dimension(400, 129));
                musicaPanel.setMaximumSize(new java.awt.Dimension(400, 129));
                telaMostrar3.add(musicaPanel);
                telaMostrar3.add(Box.createVerticalStrut(8));
            }
        }

        telaMostrar.revalidate();
        telaMostrar.repaint();
        telaMostrar2.revalidate();
        telaMostrar2.repaint();
        telaMostrar3.revalidate();
        telaMostrar3.repaint();
    }




    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel telaMostrar;
    private javax.swing.JPanel telaMostrar2;
    private javax.swing.JPanel telaMostrar3;
    private javax.swing.JLabel titulo10;
    private javax.swing.JLabel titulo11;
    private javax.swing.JLabel titulo9;
    // End of variables declaration//GEN-END:variables
}
